config/routes.rb
Rails.application.routes.draw do
  resources :trucks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/truck.rb
class Truck < ApplicationRecord
    validates :tonnage, numericality: true
    validates :crew, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]
  before_action :create_presigned_url, only: [:new, :edit]

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: 'Truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:tonnage, :crew, :image)
    end

    def create_presigned_url
      bucket = Aws::S3::Bucket.new(name: 'truck-parts')
      @signed_upload_url = bucket.presigned_post(
        key: 'public/${filename}',
        key_starts_with: 'public/',
        success_action_status: '201',
        acl: 'public-read',
        signature_expiration: 1.minute.from_now
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trucks/_form.html.erb
<%= form_with(
  model: truck,
  local: true,
  data: {
    url: signed_upload_url.url,
    fields: signed_upload_url.fields,
    host: URI.parse(signed_upload_url.url).host
  }
) do |form| %>
  <% if truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tonnage %>
    <%= form.text_field :tonnage, id: :truck_tonnage %>
  </div>

  <div class="field">
    <%= form.label :crew %>
    <%= form.text_field :crew, id: :truck_crew %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image,
      id: :truck_image
    %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form', truck: @truck, signed_upload_url: @signed_upload_url %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trucks</h1>

<table>
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Tonnage</th>
      <th>Crew</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td><%= image_tag(truck.image) %></td>
        <td><%= truck.tonnage %></td>
        <td><%= truck.crew %></td>
        <td><%= link_to 'Show', truck %></td>
        <td><%= link_to 'Edit', edit_truck_path(truck) %></td>
        <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truck', new_truck_path %>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form', truck: @truck, signed_upload_url: @signed_upload_url %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tonnage:</strong>
  <%= @truck.tonnage %>
</p>

<p>
  <strong>Crew:</strong>
  <%= @truck.crew %>
</p>

<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>